
/****************表结构****************/

  CREATE TABLE "SCOTT"."T_CHANGE_MESSAGE" 
   (	"VERSION" VARCHAR2(50) NOT NULL ENABLE, 
	"COMMITE_PERSON" VARCHAR2(10), 
	"COMMITE_DATE" VARCHAR2(50), 
	"COMMITE_MESSAGE" VARCHAR2(50), 
	"COMMITE_DIFF_ID" VARCHAR2(2900), 
	 CONSTRAINT "ID" PRIMARY KEY ("VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 


/**************本表注释**************/

		无注释


/**************本表索引**************/

INDEX_NAME(索引名称)         INDEX_TYPE(索引类型)         UNIQUENESS(唯一性约束)        COLUMNS(索引包含的字段)              
ID                           NORMAL                       UNIQUE                        VERSION                       
