
/****************表结构****************/

  CREATE TABLE "SCOTT"."T_TABLEINFORIGHT" 
   (	"TABLE_NAME" VARCHAR2(60), 
	"COLUMN_NAME" VARCHAR2(60), 
	"DATATYPE" VARCHAR2(60)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS" 


/**************本表注释**************/

		无注释


/**************本表索引**************/

		无索引
