
/****************表结构****************/

  CREATE TABLE "SCOTT"."T_CHANGE_MESSAGE" 
   (	"VERSION" VARCHAR2(50) NOT NULL ENABLE, 
	"COMMITE_PERSON" VARCHAR2(50), 
	"COMMITE_DATE" VARCHAR2(50), 
	"COMMITE_MESSAGE" VARCHAR2(50), 
	"COMMITE_DIFF_ID" VARCHAR2(50), 
	 CHECK ("VERSION" IS NOT NULL) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 


/**************本表注释**************/

		无注释


/**************本表索引**************/

		无索引
